// ============================================================================
//  FC Wängi 1967 crest bitmap (60x60 for the wall-box header).
//  Generated by tools/make_crest.py.
// ============================================================================
#pragma once

#include <stdint.h>

extern const uint16_t CREST_RGB565[];
extern const uint16_t CREST_WIDTH;
extern const uint16_t CREST_HEIGHT;
