// ============================================================================
//  FC Wängi 1967 crest data for the wall-box display.
//   - CREST_RGB565 (60x60) feeds the boot/idle pushImage at native size.
//   - CREST_SMALL_PNG (24x24) sits in the header strip and is decoded by
//     M5GFX drawPng() at runtime.
//  Both are generated by tools/make_crest.py.
// ============================================================================
#pragma once

#include <stdint.h>

extern const uint16_t CREST_RGB565[];
extern const uint16_t CREST_WIDTH;
extern const uint16_t CREST_HEIGHT;

extern const uint8_t  CREST_SMALL_PNG[];
extern const uint32_t CREST_SMALL_PNG_LEN;
extern const uint16_t CREST_SMALL_WIDTH;
extern const uint16_t CREST_SMALL_HEIGHT;
