// ============================================================================
//  FC Wängi 1967 crest data for the wall-box display.
//   - CREST_PNG (big, e.g. 130x130) is the high-quality PNG decoded by
//     drawPng() on the boot screen. Same path the header icon uses, so
//     the boot logo looks as crisp as the one in the top bar.
//   - CREST_RGB565 (legacy 60x60) is the older lossy bitmap. Kept as a
//     fallback in case CREST_PNG_LEN is 0 (e.g. partial regenerate).
//   - CREST_SMALL_PNG (24x24) sits in the header strip.
//  All generated by tools/make_crest.py.
// ============================================================================
#pragma once

#include <stdint.h>

// Big boot crest (PNG path).
extern const uint8_t  CREST_PNG[];
extern const uint32_t CREST_PNG_LEN;
extern const uint16_t CREST_WIDTH;
extern const uint16_t CREST_HEIGHT;

// Legacy RGB565 boot crest (fallback).
extern const uint16_t CREST_RGB565[];
extern const uint16_t CREST_RGB565_WIDTH;
extern const uint16_t CREST_RGB565_HEIGHT;

// Header strip icon.
extern const uint8_t  CREST_SMALL_PNG[];
extern const uint32_t CREST_SMALL_PNG_LEN;
extern const uint16_t CREST_SMALL_WIDTH;
extern const uint16_t CREST_SMALL_HEIGHT;
