// ============================================================================
//  FC Wängi 1967 crest, embedded as PNG bytes. Decoded at runtime by
//  M5GFX's drawPng() so alpha/gradients survive intact (no RGB565 banding).
//  Generated by tools/make_crest.py from tools/crest_src.png.
// ============================================================================
#pragma once

#include <stdint.h>

// Splash-screen crest (~130x130 PNG)
extern const uint8_t  CREST_PNG[];
extern const uint32_t CREST_PNG_LEN;
extern const uint16_t CREST_WIDTH;
extern const uint16_t CREST_HEIGHT;

// Header-icon crest (~24x24 PNG) — small enough to sit inside the
// 28 px tall red header strip alongside the brand text.
extern const uint8_t  CREST_SMALL_PNG[];
extern const uint32_t CREST_SMALL_PNG_LEN;
extern const uint16_t CREST_SMALL_WIDTH;
extern const uint16_t CREST_SMALL_HEIGHT;
