#!/usr/bin/env python3
"""
Generate firmware-embedded crest data from tools/crest_src.png.

Output:
  alge-controller/src/crest.cpp  PNG bytes for runtime drawPng()
                                 (preserves alpha, no RGB565 banding)
  alge-wallbox/src/crest.cpp     60x60 RGB565 array for the wallbox
                                 header (kept as bitmap because that
                                 firmware draws via pushImage)
"""
from __future__ import annotations

import io
import sys
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC  = ROOT / "tools" / "crest_src.png"
BG   = (0x0a, 0x0a, 0x0a)  # COLOR_BG_DARK — used for the RGB565 wallbox path

CONTROLLER_PNG_SIZE       = 130  # splash crest, rendered at native size
CONTROLLER_PNG_SMALL_SIZE = 24   # header crest icon
WALLBOX_RGB565_SIZE       = 60


def rgb_to_565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | ((b & 0xF8) >> 3)


def compose_on_dark(img: Image.Image) -> Image.Image:
    """Flatten RGBA onto the COLOR_BG_DARK background."""
    if img.mode != "RGBA":
        img = img.convert("RGBA")
    bg = Image.new("RGBA", img.size, BG + (255,))
    return Image.alpha_composite(bg, img).convert("RGB")


def _png_bytes(size: int) -> bytes:
    img = Image.open(SRC)
    if img.mode != "RGBA":
        img = img.convert("RGBA")
    img = img.resize((size, size), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def _bytes_to_c_array(data: bytes, name: str) -> list[str]:
    lines = [f"const uint8_t {name}[{len(data)}] = {{"]
    PER_LINE = 16
    for row_start in range(0, len(data), PER_LINE):
        chunk = data[row_start : row_start + PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return lines


def emit_controller_png(out: Path, big: int, small: int) -> None:
    """Embed two PNG byte arrays — splash crest + small header icon."""
    big_bytes   = _png_bytes(big)
    small_bytes = _png_bytes(small)

    lines = [
        "// AUTO-GENERATED by tools/make_crest.py — do not hand-edit.",
        "// Project: alge-controller",
        f"// Splash crest:  {big}x{big} PNG ({len(big_bytes)} bytes)",
        f"// Header icon:   {small}x{small} PNG ({len(small_bytes)} bytes)",
        "#include \"crest.h\"",
        "",
        f"const uint16_t CREST_WIDTH  = {big};",
        f"const uint16_t CREST_HEIGHT = {big};",
        f"const uint32_t CREST_PNG_LEN = {len(big_bytes)};",
        "",
        f"const uint16_t CREST_SMALL_WIDTH  = {small};",
        f"const uint16_t CREST_SMALL_HEIGHT = {small};",
        f"const uint32_t CREST_SMALL_PNG_LEN = {len(small_bytes)};",
        "",
    ]
    lines += _bytes_to_c_array(big_bytes, "CREST_PNG")
    lines.append("")
    lines += _bytes_to_c_array(small_bytes, "CREST_SMALL_PNG")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)} "
          f"(splash {big}x{big} = {len(big_bytes)} B, "
          f"icon {small}x{small} = {len(small_bytes)} B)")


def emit_wallbox_rgb565(out: Path, size: int) -> None:
    """RGB565 array for the wallbox firmware, which still uses pushImage."""
    img = Image.open(SRC).resize((size, size), Image.LANCZOS)
    img = compose_on_dark(img)

    pixels = list(img.getdata())
    rgb565 = [rgb_to_565(r, g, b) for r, g, b in pixels]

    lines = [
        "// AUTO-GENERATED by tools/make_crest.py — do not hand-edit.",
        "// Project: alge-wallbox",
        f"// Source:  tools/crest_src.png (resized to {size}x{size})",
        "// Format:  RGB565 little-endian, composited onto #0a0a0a.",
        "#include \"crest.h\"",
        "",
        f"const uint16_t CREST_WIDTH  = {size};",
        f"const uint16_t CREST_HEIGHT = {size};",
        "",
        f"const uint16_t CREST_RGB565[{size * size}] = {{",
    ]
    PER_LINE = 12
    for row_start in range(0, len(rgb565), PER_LINE):
        chunk = rgb565[row_start : row_start + PER_LINE]
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)} (RGB565, {size}x{size}, {len(rgb565)} px)")


def main() -> int:
    if not SRC.exists():
        print(f"missing source: {SRC}", file=sys.stderr)
        return 1
    emit_controller_png(ROOT / "alge-controller" / "src" / "crest.cpp",
                        CONTROLLER_PNG_SIZE, CONTROLLER_PNG_SMALL_SIZE)
    emit_wallbox_rgb565(ROOT / "alge-wallbox" / "src" / "crest.cpp",
                        WALLBOX_RGB565_SIZE)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
