#!/usr/bin/env python3
"""
Convert tools/crest_src.png into RGB565 C arrays for both firmware projects.

Output:
  alge-controller/src/crest.cpp  (80x80, used on the splash screen)
  alge-wallbox/src/crest.cpp     (60x60, used in the header)

RGB565 little-endian, alpha composited onto the FC Wängi background (#0a0a0a).
"""
from __future__ import annotations

import sys
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC  = ROOT / "tools" / "crest_src.png"
BG   = (0x0a, 0x0a, 0x0a)  # COLOR_BG_DARK

TARGETS = [
    (ROOT / "alge-controller" / "src" / "crest.cpp", 80, "alge-controller"),
    (ROOT / "alge-wallbox"   / "src" / "crest.cpp", 60, "alge-wallbox"),
]


def rgb_to_565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | ((b & 0xF8) >> 3)


def compose(img: Image.Image) -> Image.Image:
    """Flatten RGBA onto the dark background."""
    if img.mode != "RGBA":
        img = img.convert("RGBA")
    bg = Image.new("RGBA", img.size, BG + (255,))
    return Image.alpha_composite(bg, img).convert("RGB")


def emit(out: Path, size: int, project: str) -> None:
    img = Image.open(SRC)
    img = img.resize((size, size), Image.LANCZOS)
    img = compose(img)

    pixels = list(img.getdata())
    rgb565 = [rgb_to_565(r, g, b) for r, g, b in pixels]

    lines = [
        "// AUTO-GENERATED by tools/make_crest.py — do not hand-edit.",
        f"// Project: {project}",
        f"// Source:  tools/crest_src.png (resized to {size}x{size})",
        "// Format:  RGB565 little-endian, composited onto #0a0a0a.",
        "#include \"crest.h\"",
        "",
        f"const uint16_t CREST_WIDTH  = {size};",
        f"const uint16_t CREST_HEIGHT = {size};",
        "",
        f"const uint16_t CREST_RGB565[{size * size}] = {{",
    ]
    # 12 values per line for readable diffs.
    PER_LINE = 12
    for row_start in range(0, len(rgb565), PER_LINE):
        chunk = rgb565[row_start : row_start + PER_LINE]
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)} ({size}x{size}, {len(rgb565)} px)")


def main() -> int:
    if not SRC.exists():
        print(f"missing source: {SRC}", file=sys.stderr)
        return 1
    for out, size, project in TARGETS:
        emit(out, size, project)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
